services:
  - type: web
    name: chronos-api
    env: docker
    dockerfilePath: Dockerfile
    port: 8123
    envVars:
      - key: REDIS_URI
        value: redis://langgraph-redis:6379
      - key: LANGSMITH_API_KEY
        value: ${LANGSMITH_API_KEY}
      - key: DATABASE_URI
        value: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
    buildCommand: ./build.sh
    startCommand: langgraph dev --port 8000
    healthCheckPath: /health

  - type: redis
    name: langgraph-redis
    image: redis:6
    healthCheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 1s
      retries: 5

  - type: postgres
    name: langgraph-postgres
    image: postgres:16
    port: 5433
    envVars:
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
    healthCheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      startPeriod: 10s
      timeout: 1s
      retries: 5
      interval: 5s
    volumes:
      - name: langgraph-data
        mountPath: /var/lib/postgresql/data

volumes:
  - name: langgraph-data
    driver: local