services:
  # Redis Service
  - type: redis
    name: chronos-redis
    plan: free
    envVars:
      - key: REDIS_URI
        value: redis://chronos-redis:6379

  # PostgreSQL Service
  - type: postgres
    name: chronos-db
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres

  # API Service
  - type: web
    name: chronos-api
    env: docker
    build:
      dockerfile: Dockerfile
      context: .
    port: 8000
    envVars:
      - key: REDIS_URI
        value: redis://chronos-redis:6379
      - key: DATABASE_URI
        value: postgres://postgres:postgres@chronos-db:5432/postgres?sslmode=disable
      - key: LANGSMITH_API_KEY
        value: ${LANGSMITH_API_KEY} # Set this in Render's environment variables
    healthCheckPath: /health