services:
  # Redis Service
  - type: redis
    name: langgraph-redis
    plan: free
    envVars:
      - key: REDIS_URI
        value: redis://langgraph-redis:6379

  # PostgreSQL Service
  - type: postgres
    name: langgraph-postgres
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: postgres
      - key: POSTGRES_USER
        value: postgres
      - key: postgres
        value: postgres

  # LangGraph API Service
  - type: web
    name: langgraph-api
    env: docker
    build:
      dockerfile: Dockerfile
      context: .
    port: 8000
    envVars:
      - key: REDIS_URI
        value: redis://langgraph-redis:6379
      - key: DATABASE_URI
        value: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
      - key: LANGSMITH_API_KEY
        value: ${LANGSMITH_API_KEY} # Set this in Render's environment variables
    healthCheckPath: /health